CompilerExtension: default empty costructor
This prevents the following error and improves BC.
ReflectionException: Class Nette\DI\Extensions\PhpExtension does not have a constructor, so you cannot pass any constructor arguments